export const dailyItineraryLocations = [
    {
        key: 'jp-tokyo',
        country: '日本',
        city: '東京',
        displayName: '日本, 東京',
        weatherMapping: 'Tokyo',
    },
    {
        key: 'jp-osaka',
        country: '日本',
        city: '大阪',
        displayName: '日本, 大阪',
        weatherMapping: 'Osaka',
    },
    {
        key: 'jp-nagoya',
        country: '日本',
        city: '名古屋',
        displayName: '日本, 名古屋',
        weatherMapping: 'Nagoya',
    },
    {
        key: 'jp-kyoto',
        country: '日本',
        city: '京都',
        displayName: '日本, 京都',
        weatherMapping: 'Kyoto',
    },
    {
        key: 'jp-hokkaido',
        country: '日本',
        city: '北海道',
        displayName: '日本, 北海道',
        weatherMapping: 'Sapporo',
    },
    {
        key: 'jp-kumamoto',
        country: '日本',
        city: '熊本',
        displayName: '日本, 熊本',
        weatherMapping: 'Kumamoto',
    },
    {
        key: 'tw-taipei',
        country: '台灣',
        city: '台北',
        displayName: '台灣, 台北',
        weatherMapping: 'Taipei',
    },
    {
        key: 'tw-taoyuan',
        country: '台灣',
        city: '桃園',
        displayName: '台灣, 桃園',
        weatherMapping: 'Taoyuan',
    },
    {
        key: 'tw-taichung',
        country: '台灣',
        city: '台中',
        displayName: '台灣, 台中',
        weatherMapping: 'Taichung',
    },
    {
        key: 'tw-kaohsiung',
        country: '台灣',
        city: '高雄',
        displayName: '台灣, 高雄',
        weatherMapping: 'Kaohsiung',
    },
    {
        key: 'tw-hualien',
        country: '台灣',
        city: '花蓮',
        displayName: '台灣, 花蓮',
        weatherMapping: 'Hualien',
    },
    {
        key: 'tw-taitung',
        country: '台灣',
        city: '台東',
        displayName: '台灣, 台東',
        weatherMapping: 'Taitung',
    },
];
